### ISSUE TITLE
Ignore commits/PRs from Bot type accounts

### ISSUE THREAD

**Issue by Nimphal** [ministryofjustice/github-repository-standards#30]
There is a user type called "Bot" on Github and Dependabot is that type that of account. When we are checking for recent commits on repositories, we should ignore ones that are made by a Bot account.

NB: This will work for Dependabot, but there isn't a guarantee it will solve all our woes. The Snyk bot account does not seem to have been created as a type Bot.

**Comment by NickWalt01** [comment]
Python code now uses the last commit date to decide if repo should be archived or not and ignores the dependabot branches See https://github.com/ministryofjustice/operations-engineering/blob/27619f257c2e4787ae6d0df1b9baf9e78631f3ed/scripts/python/archive-repositories.py#L43
