### ISSUE TITLE
Duplicated repo on the report

### ISSUE THREAD

**Issue by colinbruce** [ministryofjustice/github-repository-standards#52]
Hi, I was checking the report for the services my team support and there is a duplicated entry for legal-framework-api
![image](https://user-images.githubusercontent.com/6757677/222668166-49d15376-fb23-4733-b1a6-10db9ba72388.png)
Both point to the single repo (https://github.com/ministryofjustice/legal-framework-api) in the organisation! 😟

**Comment by NickWalt01** [comment]
Hello @colinbruce thanks for highlighting that bug, we will have a look at it, am doing some work on the repo at the moment so it is good timing to get it fixed

**Comment by NickWalt01** [comment]
This ticket has been raised on this repo, I believe the error may be in the ops-eng python flask repo when reading the json data and creating the tables for public and private repo's. Will investigate that repo next.

**Comment by NickWalt01** [comment]
Added [code](https://github.com/ministryofjustice/operations-engineering-reports/pull/107) in the ops-eng-report repo to remove duplicates entries in the json data from being added to the report pages.

**Comment by NickWalt01** [comment]
Duplicates have been removed:

Private
Before = 709 with 37 compliant and 672 not compliant
After = 704 with 37 compliant and 667 not compliant

Public
Before = 709 with 322 compliant and 387 not compliant
After = 699 with 316 compliant and 383 not compliant

**Comment by NickWalt01** [comment]
Duplicates have been removed:

Private
Before = 709 with 37 compliant and 672 not compliant
After = 704 with 37 compliant and 667 not compliant

Public
Before = 709 with 322 compliant and 387 not compliant
After = 699 with 316 compliant and 383 not compliant
